project:
  type: website
  output-dir: docs

website:
  title: "SEL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Team.qmd
      - contact.qmd

format:
  html:
    theme: yeti
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true
    



